### ISSUE TITLE
UX: Clicking on filetree items clears command + parametrization

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-gooey#105]
If I start drafting a command, but then navigate around in the file tree or accidentally click an item in it, my command draft is gone. It would be nice if I could keep it around, I feel like I would turn to clicking on items in the file tree to remind myself of paths etc
![Peek 2022-09-16 11-25](https://user-images.githubusercontent.com/29738718/190605215-42d65c5a-033f-48b6-8f3c-3951b433c49c.gif)

**Comment by mih** [comment]
Behavior was requested in https://github.com/datalad/datalad-gooey/issues/57
