### ISSUE TITLE
Changing Path Icon?

### ISSUE THREAD

**Issue by Manukapp** [datalad/datalad-gooey#111]
Not directly intuitive understanding of the left arrow VS up arrow for opening folder VS path to file. 

**Suggesting a rectangle for folder search**

**Comment by mih** [comment]
We could also reuse the file vs dir icons from the tree. WDYT @jsheunis ?

**Comment by jsheunis** [comment]
Yes, sounds more intuitive that way 👍

**Comment by Manukapp** [comment]
Unfortunately, no icons are visible on Windows, see video in #114
