### ISSUE TITLE
Datalad Clone path unclear on Windows

### ISSUE THREAD

**Issue by Manukapp** [datalad/datalad-gooey#116]
`datalad clone` requires **path to file** specification otherwise it may clone git repository beyond gooey's grasp, i.e. a folder a hierarchy above the highest folder of the GUI. 
Importantly, **path to folder** specification leads to **install(error)** `[target path already exists and not empty, refuse to clone into target path]`

### **Default path is home possibly?** 
This may explain the above problem. For me, the default path is Desktop, as verified with tree command: path box had '.' 
However, datalad gooey was open for a folder (named Gooey) **_inside_** Desktop, **but** displayed tree starting from Desktop, not Gooey folder

Example in screenshot

![dataladcloneerrorGUI](https://user-images.githubusercontent.com/86295664/190632821-32f6ea93-dbfe-4691-8e69-4f16c13543bc.png)

**Comment by adswa** [comment]
linking #106

**Comment by mih** [comment]
I have registered the ideas here in #106 -- will close this one, as they are closely related.
