### ISSUE TITLE
Did datalad save do anything? on Windows

### ISSUE THREAD

**Issue by Manukapp** [datalad/datalad-gooey#117]
**Can't tell whether datalad save tracked anything.** The specified path (path box) in datalad save remains 'untracked'. 

Same for **right clicking** on the folder of the dataset we want to save and then `datalad save`. Through this latter method, the path is automatically implemented in the 'dataset' box. **Nevertheless**, I cannot tell whether any changes were saved. 

This may be related to #116

**Comment by adswa** [comment]
please do ``git checkout main && git pull origin main`` first

**Comment by mih** [comment]
I this still an issue?

**Comment by Manukapp** [comment]
I managed to save as mentioned in this comment: https://github.com/datalad/datalad-gooey/issues/181#issuecomment-1254678643 .
