### ISSUE TITLE
Status bar does not prompt unsuccessful on Windows

### ISSUE THREAD

**Issue by Manukapp** [datalad/datalad-gooey#120]
Status bar remains on `'started get'` same for `datalad save`. No prompt saying task is unsuccessful, following #117. For `datalad get`, I tried `on_failure` with stop option, but the status bar did not change and remained unsuccessful for the case specified below.

**Unsuccessful** `datalad get` is the case for (stimulus) audio files from a open neuro dataset. **However,** this is not the case for nifti files: Log console displays `get(ok)` and the status bar shows: `'Finished 'gooey_status_light'`.

**Comment by adswa** [comment]
I can reproduce this for studyforrest data, but haven't investigated closely what happens.

**Comment by adswa** [comment]
Another observation: ``get`` starts and finishes (complete with progress bars in the terminal) when I do not specify a path, but instruct to get a complete dataset.
It fails to retrieve all files in the studyforrest dataset, but I think that is a different issue (failing to follow the redirected metadatasrc) - that shows at least that ``get(error)...`` messages nicely make it into the log.

**Comment by adswa** [comment]
I retested, and the behavior is better now! The status bar displays a ``get`` failure upon an unsuccesful get, and there is a traceback in the Console/Log.

**Comment by Manukapp** [comment]
For me it improved in the sense that the status bar says 'failed', but the current situation points to another error. This seems related to #143 

Cmd line message:

`{'dataset': 'C:\\Users\\Leo\\Desktop\\Gooey\\Windy\\inputs\\Narratives',
 'path': [WindowsPath('C:/Users/Leo/Desktop/Gooey/Windy/inputs/Narratives/sub-002/anat')]}
EXECINTHREAD get {'path': [WindowsPath('C:/Users/Leo/Desktop/Gooey/Windy/inputs/Narratives/sub-002/anat')]} {}`

![image](https://user-images.githubusercontent.com/86295664/191224936-f1a84f5b-6096-4fb1-b049-bb8d09483486.png)

**Comment by mih** [comment]
I am closing this issue. It sounds like the original problem is solved. Additional observations related to #143 should go there.
