### ISSUE TITLE
Make Git(?) ask for credentials via GUI

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-gooey#123]
I tried to reproduce #119 and forgot to create a GitHub sibling with SSH protocol. Pushing to Github then hung. Restarting queried for credentials in the terminal:
![Screenshot from 2022-09-16 14-59-54](https://user-images.githubusercontent.com/29738718/190644828-9ced7817-9540-4898-8f5b-f97c12c730ea.png)

Also, some stderr must have been swallowed somewhere, causing the application to stall forever, because the typical "Github deprecated user-password auth" error was not propagated.

**Comment by adswa** [comment]
However, it asks nicely for tokens (here a screenshot of ``create_sibling_github``:
![gooey4](https://user-images.githubusercontent.com/29738718/190666588-84bef0ce-34ee-427c-a434-f6f0fd71281e.png)

**Comment by mih** [comment]
I re-titled the issue with a speculation what this is about. I suspect the prompt in the terminal is not datalad but git. All datalad UI questions should come via GUI already.

**Comment by mih** [comment]
Since c4ad405303f6d385baef2cc6aba9cd03f1964719 Git must not use the terminal for interaction anymore. Since 042577d10c5f5d2d8e097e1e875d0ef1fc9f80b9 a gooey-specific ASKPASS helper is used to route all credential requests from Git and SSH to the GUI.
