### ISSUE TITLE
Test failures due to no graphical interface in CI setup

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-gooey#13]
Looking at the test failure: We are now trying to start the GUI, but no CI setup has a graphical interface, hence all fail, including the doc-builds. I think there is little point in doing this startup test unconditionally.

_Originally posted by @mih in https://github.com/datalad/datalad-gooey/issues/12#issuecomment-1231227237_

**Comment by yarikoptic** [comment]
FWIW, if desired, could always be done via xvfb-run as we do for testing in some debian packages.
