### ISSUE TITLE
Windows app shows no icons

### ISSUE THREAD

**Issue by Manukapp** [datalad/datalad-gooey#140]
No icons on the tree!

No Icons in path specification boxes. See video.

[path_crash.webm](https://user-images.githubusercontent.com/86295664/190993391-6b98aebe-afdd-4c23-b1a3-8153a679f0b2.webm)

**Comment by mih** [comment]
OK, interesting. Thanks for the report. I see no errors in the terminal. It seems the approach to icon loading is broken on windows.

**Comment by Manukapp** [comment]
SVG files can be supported with an extra installation: 
https://techcommunity.microsoft.com/t5/windows-10/svg-support-in-windows10-file-explorer/m-p/1197707

See how my Windows uses Microsoft Edge for opening .svg files

![image](https://user-images.githubusercontent.com/86295664/191000824-89e8f1b5-7b72-4b58-b7e7-3ca13bc06e0b.png)

**Comment by adswa** [comment]
How did you install datalad-gooey exactly, @Manukapp?

**Comment by mih** [comment]
We need more information to be able to act here. What version of windows is this, what version of pyside.

I doubt that the abilities of the windows explorer have an impact here.

**Comment by Manukapp** [comment]
### Installation 
in python venv, datalad clone of https://github.com/datalad/datalad-gooey.git 
Followed by `pip install -e .` 
And `git pull`ed on a new day.

### Versions 
Windows 10 Home
Pyside6 version: 6.3.2

### SVG
Explorer (now called Edge!!) is the default app that appeared to open svg, but it opens a tab on Edge. I do not have any default svg reader, which can be installed. Currently found a software that may help (needs reboot, brb)

**Comment by mih** [comment]
@Manukapp reports via chat that the new installer fixes the issue.
