### ISSUE TITLE
Error executing Save AND Get

### ISSUE THREAD

**Issue by Manukapp** [datalad/datalad-gooey#143]
**Using right click on directory**, both `datalad save` and `datalad get` fail to execute, displaying a similar error regarding their respective .py scritps, namely cmd_exec error, and **"unspecified dataset"**. However, because I right click, the dataset is immediately specified. **See screenshot.**

![image](https://user-images.githubusercontent.com/86295664/190996051-b5bd7efc-7768-4318-a03f-92289530d596.png)

**Comment by adswa** [comment]
I think this is another example of #145, not specific to save or get. I would suggest to close this issue in favour of #145
