### ISSUE TITLE
Document path specification for creating new datasets

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-gooey#144]
If I supply a path like ``/tmp`` to clone it will refuse to clone a dataset inside, because it attempts a ``datalad clone <source> /tmp`` instead of a ``datalad clone <source> tmp/<dsname>``. 
![Screenshot from 2022-09-19 12-19-33](https://user-images.githubusercontent.com/29738718/190996981-03ec9ef6-13f0-44a6-99ef-668f21ade5cd.png)
However, I can't hand-edit the path specification (which I don't think is bad). I'd intuitively expect that when I select `/tmp` as a path, clone would create `/tmp/<ds-i-wanted-to-clone>`.

**Comment by mih** [comment]
Right now, you could chose the path picker and select any path, including a non-existing directory.

**Comment by Manukapp** [comment]
### How would you select a non-existing directory?   
Clone was successful when creating a new folder in the path picker, and selecting that new folder (here it is the path written after `install(ok)`)
However, trying to select a new folder does not work, as seen in Screenshot. I also attempted `currentdir`/`non-existingdir` (and \)
   
![image](https://user-images.githubusercontent.com/86295664/191005025-f6723682-13ca-49fd-8ab8-513781aa370c.png)

**Comment by mih** [comment]
Non-existing paths can be "selected" by opening the file-picker (not the directory picker), and then navigate to the parent path of the non-existing target directory. Now you can type the name in the "File name" field and hit return.

Alternatively, one can use the directory picker too, navigate to the parent directory of the target, and then actually create the target directory in the dialog (there is a "plus" button), select that and hit return.

**Comment by adswa** [comment]
I think we should ensure that this is carefully documented.

**Comment by mih** [comment]
With #191 we can annotate command to cause a directory picker widget. This would then be used to select an existing directory -- which can also be created directly by the user within the selection dialog.

I think this is intuitive

**Comment by Manukapp** [comment]
Exploring this issue for `create` and `clone`,  yet only directory picker is available, no file picker and thus it is impossible to pick a non-existing path. I agree it is simpler in this manner. **In addition**, Windows file explorer allows to create a `New Folder` from the directory picker prompt, see screenshot below. **I believe we should close this issue (I am not allowed)**

![image](https://user-images.githubusercontent.com/86295664/192500450-3f990426-cd79-40a7-9db0-6f65df6a2aca.png)

**Comment by mih** [comment]
I agree. Thanks for the feedback!
