### ISSUE TITLE
Fix differentiation between files in `git` and `git-annex`

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-gooey#149]
While writing a test for `fsbrowser_item.py`, I saw this code in [`update_from_status_result()`](https://github.com/datalad/datalad-gooey/blob/2a5409552c7391fba9d47711640c2d4b270c75b0/datalad_gooey/fsbrowser_item.py#L95-L119):

```python
type_ = res.get('type')
if type_:
    # guess by type, by default
    type_icon = None
    if type_ == 'file':
        # for files we can further differentiate
        type_icon = 'file-annex'
        if res.get('key'):
            type_icon = 'file-git'
```

Isn't it an annexed file that would have the `key` property. If so, and unless I'm misunderstanding, shouldn't that part of the code read:

```python
        type_icon = 'file-git'
        if res.get('key'):
            type_icon = 'file-annex'
```

**Comment by adswa** [comment]
I think you're assessment is correct, it should be the other way around

**Comment by mih** [comment]
Yes, same here. The current implementation is wrong.
