### ISSUE TITLE
Is it possible to only request a directory path for individual commands?

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-gooey#153]
In the simplified theme, ``create``'s "Create at" parameter widget has a file and path picker. I don't think it makes sense to be able to select files for this argument. Can it be removed (so that only the directory picker is usable) for individual commands?

**Comment by mih** [comment]
We would need to think where and how to override that. The `create` command itself is not even aware that it wants to receive a path specification for this parameter.

Maybe we start implementing our own `Constraint` definitions, and provide them via an override in the API specification?

If that finds agreement, I can give it a go. It would also help to pull out the special handling of the `dataset` argument from the code.

For create, we would need `EnsureNonExistingOrDirectoryPath`, same as for any `dataset` argument.

**Comment by mih** [comment]
Maybe we can start with a `EnsureExistingDirectory` and trigger a directory picker. This would require users to actually say what a target dir is, and maybe resolve the confusion expressed in https://github.com/datalad/datalad-gooey/issues/144
