### ISSUE TITLE
Must emit immutable dicts in signals

### ISSUE THREAD

**Issue by mih** [datalad/datalad-gooey#159]
In contrast to my assumptions, the signal/slot message passing does not involve copying of the signal payload. The very same instances are taken from the sender and passed to all receivers.

This means that mutable data types like `dict` can be modified by any receiver, and all following receivers.

I propose that we switch away from `dict` in any slots, and move to ` MappingProxyType`, which essentially provides a dict-interface to a seemingly immutable data structure.

https://docs.python.org/3/library/types.html#types.MappingProxyType

Using this in all signal definitions and emissions will cause any mutable operation to raise an exception and safe as the trouble of dissecting complex interactions.

**Comment by bpoldrack** [comment]
From docs:

> It provides a dynamic view on the mapping’s entries, which means that when the mapping changes, the view reflects these changes.

This seems to suggest, that a sender emitting a proxy from its internal dict would still be able to change that dict after signal emission with consequences for receivers.
Why not mandate receivers to get themselves a copy?

**Comment by mih** [comment]
Is that "Eigenverantwortung"? I heard about it in the news.

**Comment by bpoldrack** [comment]
Because emitting a signal does not prevent the sender from proceeding to do more with the dict. Hence, it doesn't solve the problem really. If you're unaware of this effect when you write a sender, you can still screw it up.
With the proxy we only enforce read-only operation for the receivers. Not sure, why this would be better.

**Comment by mih** [comment]
I have one sender, 1k receivers. I send an immutable type once, and 1k receivers do not need to make a copy. I think this is an advantage.

Whether or not the sender thinks it is a good idea to make changes afterwards (in callbacks there hardly ever is an afterwards), is a different question IMHO.
