### ISSUE TITLE
Multivalue Path Widget passes default value on

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-gooey#181]
I saw this on both Windows and Debian, but it would be good if someone could confirm this on a system without file picking crashes.

I observed ``save`` failures on 36f47a092e0 (current main) when I manually added a specific path to be saved (i.e., clicking + in the path picker and selecting a path via one of the path/directory pickers). The traceback looked like this:
```
Running: Dataset('C:\\Users\\adina\\Desktop\\studyforrest').save(path=[], message='testing', recursion_limit=0, to_git=False, on_failure='ignore') failed!
Traceback (most recent call last):
  File "c:\users\adina\repos\datalad-gooey\datalad_gooey\dataladcmd_exec.py", line 156, in _cmdexec_thread
    for res in cmd(**cmdkwargs):
  File "c:\users\adina\repos\datalad\datalad\interface\utils.py", line 357, in generator_func
    for r in _process_results(
  File "c:\users\adina\repos\datalad\datalad\interface\utils.py", line 544, in _process_results
    for res in results:
  File "c:\users\adina\repos\datalad\datalad\core\local\save.py", line 226, in __call__
    for s in Status()(
  File "c:\users\adina\repos\datalad\datalad\interface\utils.py", line 357, in generator_func
    for r in _process_results(
  File "c:\users\adina\repos\datalad\datalad\interface\utils.py", line 544, in _process_results
    for res in results:
  File "c:\users\adina\repos\datalad\datalad\core\local\status.py", line 397, in __call__
    for res in _yield_paths_by_ds(ds, dataset, ensure_list(path)):
  File "c:\users\adina\repos\datalad\datalad\core\local\status.py", line 621, in _yield_paths_by_ds
    paths_by_ds, errors = get_paths_by_ds(refds, dataset_arg, paths)
  File "c:\users\adina\repos\datalad\datalad\core\local\status.py", line 541, in get_paths_by_ds
    paths = [(resolve_path(p, dataset_arg), str(p)) for p in paths]
  File "c:\users\adina\repos\datalad\datalad\core\local\status.py", line 541, in 
    paths = [(resolve_path(p, dataset_arg), str(p)) for p in paths]
  File "c:\users\adina\repos\datalad\datalad\distribution\dataset.py", line 651, in resolve_path
    elif not Path(p).is_absolute():
  File "C:\Users\adina\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\Users\adina\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\adina\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not type
```

The log message in the command log seemed to suggest that file picking didn't succeed (``path=[]``)
```
Running: Dataset('C:\\Users\\adina\\Desktop\\studyforrest').save(path=[], recursion_limit=0, to_git=False, on_failure='ignore')
```

But the terminal showed that instead of ``[]``, the initial default value of `newitem.setData` was used. 

```
EXECINTHREAD save {'dataset': 'C:/Users/adina/Desktop/studyforrest', 'path': [<class 'datalad_gooey.utils._NoValue'>], 'message': 'testing', 'recursion_limit': 0, 'to_git': False, 'on_failure': 'ignore'} {}
```

I replicated this on Debian, and the following patch 

```diff
diff --git a/datalad_gooey/param_multival_widget.py b/datalad_gooey/param_multival_widget.py
index f3695b4..ce8c372 100644
--- a/datalad_gooey/param_multival_widget.py
+++ b/datalad_gooey/param_multival_widget.py
@@ -136,7 +136,7 @@ class MultiValueInputWidget(QWidget, GooeyParamWidgetMixin):
         # give it a special value if nothing is set
         # this helps to populate the edit widget with existing
         # values, or not
-        newitem.setData(Qt.EditRole, _NoValue)
+        newitem.setData(Qt.EditRole, '/tmp')

```

revealed that the selection from the path picker did not make it into the command spec
![image](https://user-images.githubusercontent.com/29738718/191686311-4a04cd94-25f2-4c47-9db8-22156ff2b99e.png)

I then selected ``save`` from the right-click directory menu on a single file. In this case, everything worked. Adding an additional file (clicking '+', selecting a file with the path picker) caused the crash again.
![pathgooey2](https://user-images.githubusercontent.com/29738718/191689200-0d337d22-6b18-4fd8-a79a-ced5119525b9.png)
 The Command log did not hint at wrong paths:
```
Running: Dataset('C:\\Users\\adina\\books2').save(path=['C:\\Users\\adina\\books2\\D.C.C.MacKay-Information_Theory_Inference_and_Learning_Algorithms.pdf', ], recursion_limit=0, to_git=False, on_failure='ignore') failed! (see error log for details)
```
But the terminal did: 
```
EXECINTHREAD save {'dataset': 'C:\\Users\\adina\\books2', 'path': ['C:\\Users\\adina\\books2\\D.C.C.MacKay-Information_Theory_Inference_and_Learning_Algorithms.pdf', <class 'datalad_gooey.utils._NoValue'>], 'recursion_limit': 0, 'to_git': False, 'on_failure': 'ignore'} {}
```

I saw the same with the directory picker instead of the file picker. When it was automatically filled, the correct paths were passed on. When I selected directories manually, my selected paths were not propagated.

**Comment by Manukapp** [comment]
### Using windows installer by @christian-monch 
Selecting Path with right-click for `datalad save` worked successfully, for the **first time** on my PC!

![image](https://user-images.githubusercontent.com/86295664/191693212-5caddab2-2d87-4d62-9eb6-c481e08ad76a.png)

**Comment by adswa** [comment]
I also saw this work with right click, which is great! Can you also try with 'save' from the Dataset menu, or by adding an additional file by clicking on the + button?

**Comment by Manukapp** [comment]
I have tried and it comes with the same error as for `datalad get` , mentioned in [#114 #](https://github.com/datalad/datalad-gooey/issues/114#issuecomment-1254666835)

**Comment by bpoldrack** [comment]
Ping #175

**Comment by bpoldrack** [comment]
Ok, reproduced. (Thx, @adswa).
Clicking into the editline (triggering modified) and then picking the path is the culprit.

**Comment by bpoldrack** [comment]
So, I observe this in fact with any edit of the path's `QLineEdit` (including the "no edit" by simply clicking in it, but not typing anything) before clicking on the file path selector button. In that case, the subsequently filled in path from the dialog sets the `PathParamWidget`'s value correctly, but doesn't trigger `MyItemDelegate.setModelData`. Therefore the model's `_NoValue` is ultimately delivered.
When going straight for the dialog instead w/o editing before, `MyItemDelegate.setModelData` is triggered and everything is fine.

I have not yet figured, how that can be. I suspected the `editingFinished` signal missing, but that doesn't appear to be the case.


In some sense, we may be able to live with it for now, since in simplified API the field is not editable anyway. But: I do suspect, that not having this ironed out is connected to the crash observed on test cleanup for `test_paramwidget` as well as #114.

**Comment by bpoldrack** [comment]
In fact, checking in on the test's crash via `gc.get_objects` gives me: `'Internal C++ object (PySide6.QtWidgets.QDialogButtonBox) already deleted.'`. That sounds quite like what @adswa found in context of #114
