### ISSUE TITLE
Windows .exe installation behaviour

### ISSUE THREAD

**Issue by Manukapp** [datalad/datalad-gooey#184]
Succesful installation from the element chat app (**not from here**: https://files.inm7.de/cristian/)

### **Double click the .exe file**
![image](https://user-images.githubusercontent.com/86295664/191713939-a7f09ed0-9098-4fd3-94b3-947486cc95f1.png)

Go to more info and `run anyway`. 

### **Installs Git & git-annex**

![image](https://user-images.githubusercontent.com/86295664/191714200-8cffa5e1-b009-4bf0-a209-734e1f4c252f.png)

Follow Git & git-annex installation until end.

### **Installing Datalad Gooey**

It does this, yet stays stuck at this point:
![image](https://user-images.githubusercontent.com/86295664/191714373-16fa285a-93db-49fc-bfb9-e84d65b44991.png)

### **Triggering pip install?**
I randomly pressed some keys while in the python cmd prompt that appears with the installation, and it triggered the installation, looks like `pip install`

![image](https://user-images.githubusercontent.com/86295664/191714512-c5cf1db6-7ccb-4bf3-a74e-aac4637ccd3d.png)

### **Completed Installation**
Following pip installation, the installtion process is complete.

![image](https://user-images.githubusercontent.com/86295664/191714767-6805d7ce-37c7-4d2e-98c5-b73adc0b8c7e.png)

**Comment by adswa** [comment]
I tried the installer, too, copying it from juseless ``/data/group/psyinf``. I added my observations here: https://github.com/datalad/datalad-gooey/issues/83#issuecomment-1254786958
