### ISSUE TITLE
Reverse parameter order for create-sibling-* commands

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-gooey#194]
In simple view, the ``create-sibling-*`` commands' parameters seem to be in an order that is reverse from what they should be:

![image](https://user-images.githubusercontent.com/29738718/191747698-08d45c22-ca67-45a2-a886-1aadf7a99348.png)
![image](https://user-images.githubusercontent.com/29738718/191748094-6d25456a-54d9-4e12-91b3-f8d2695287ea.png)

The complete API has a sane order of parameters.

**Comment by mih** [comment]
The complete API has an order that matched the command signature. In the simplified API the selection and order is hand-crafted. Those commands have not been touched. Will add a TODO list to https://github.com/datalad/datalad-gooey/issues/132
