### ISSUE TITLE
How about a help tab?

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-gooey#198]
![image](https://user-images.githubusercontent.com/29738718/191763323-4a621731-592a-4cf4-b47e-903ba9a6b790.png)

'Report a problem' could be a hyperlink to a new issue on Github. 'About' could link to datalad.org. Tutorials could link to the gooey docs or the handbook.

**Comment by mih** [comment]
I like!

**Comment by adswa** [comment]
done in #199
