### ISSUE TITLE
SVG icons

### ISSUE THREAD

**Issue by mih** [datalad/datalad-gooey#2]
QSvgRenderer can render directly onto QImage instances. Which can also save the image, useful for caching, in case the SVG rendering is slow.

**Comment by jsheunis** [comment]
Took a first shot at some icons here: https://github.com/jsheunis/datalad-gooey/tree/enh/issue-2/datalad_gooey/resources/icons

Haven't tested them in the context of the app and #5

Looking for comments (or their absence) before I create a PR to address #2 and #5.

**Comment by aqw** [comment]
The source of some of the icons includes references to Font Awesome Pro, the license of which is non-Free: https://fontawesome.com/license#what-creators-may-not-do

```
<!--! Font Awesome Pro 6.1.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. -->
```

The link icon at least (I did not check the others) seems to be "[Classic Solid Link](https://fontawesome.com/icons/link?s=solid&f=classic)", which is a non-Pro glyph on the website. But, confusingly, still lists the commercial license.

v4 and v5 were still Free. I don't see explicit reference to v6 being Free (though it's strongly implied). The [Free license](https://fontawesome.com/license/free) on the Font Awesome website suggests that it's still current.

We should verify that V6 is Free. If so, the license should be updated appropriately (I believe CC-BY). If V6 is non-Free, then the easiest solution is to use the v4 versions, which are explicitly advertised as Free. https://fontawesome.com/v4/license/

**Comment by jsheunis** [comment]
Update: I'm looking into this issue further, once I understand the implementation to state annotations done in https://github.com/datalad/datalad-gooey/commit/cfd994ddbd0f1ae96a0ba09a70a71c76f3a63549.

**Comment by mih** [comment]
I think we now are doing good here.
