### ISSUE TITLE
Initial user feedback

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-gooey#21]
I am creating this issue to list all the points of feedback that I thought of when testing the GUI locally (MacOS). 

Disclaimers: Some of my expectations might not be in line with the design decisions made/planned for the GUI. Some issues might already be known. Some might not be issues at all.

From this list, we can create new and separate issues per topic if so desired. I'm dumping it all in a list for now just to make it easy for myself.

1. It would be cool to have an immediate visual representation (with icons) of what is a dataset and what is not. Distinctions could extend to content in git vs annex, etc. I am aware of #2 and #5.
2. I would expect the content in the Actions/Properties/History tab to be responsive to user selections in the file browser tab. A simple current example is that the content of the last executed action in the top right tab will remain visible (in a greyed-out state) even when selecting a different dataset in the file browser or when selecting a different toolbar option and then selecting "Action" again.
3. I'm assuming the available dataset actions are derived from what is available in the environment from which the GUI is launched, because I can e.g. see actions from datalad extensions. This is great. (more of a comment than an issue 😄 )
4. I tried running some commands (`meta_extract`, `search`, `create`),  but none seem to execute, and no output is seen in the Log tab. Perhaps this should work yet. In either case, my expectation would be for the full command line output to show in the Log/Console tab, including results records/summaries as well as exceptions/warnings, and for the file browser to update in case changes were made there (e.g. a newly created dataset)
5. Properties of a dataset also seem like something that users would expect as a menu item in the right-click dropdown.
6. I think we need to find an intuitive and consistent way to deal with how users find and select information/options. The right click as well as tab selection options could be duplicating functionality in some ways, and this could confuse users.

To be continued...

**Comment by mih** [comment]
Thanks! This all makes sense, or is true.

**Comment by mih** [comment]
I think this is all addressed now in some ways -- it least as roughly as outlined here. I'd say we close this compound issue and focus on more focused ones.
