### ISSUE TITLE
Dump of info from discussion on a rewrite of the parameter widgets

### ISSUE THREAD

**Issue by mih** [datalad/datalad-gooey#212]
it seems that all logic minus init_gooey_from_other_param() goes away
it is called in three ways
with the respective parameters default
with the respective parameters value
with other parameter values

setting a value is then internal

getting a value implements a plain retrieval of what a widget thinks the native dtype would be (not a label)
There is no handling of _NoValue per widget
There is no concept of default in the widget, only a concept of "current value"

set_gooey_param_spec() also goes away and becomes an internal of the mixin, that stores the name only

what is needed is, that all classes can actually be set to the default value.

the only access of information from the mixin within the context of the widget would be the name, the docs, and no more

MultiValue needs to get_gooey_param_spec from the children. It will retrieve _NoValue and skip the thing when delivering its list upwards.

**Comment by bpoldrack** [comment]
> set_gooey_param_spec() also goes away and becomes an internal of the mixin, that stores the name only

It also keeps storing the default value and calls `set_default`. `set_default` also is a MixIn method that differs from set_gooey_param_value only in that it doesn't emit value_changed to avoid a double-update.

**Comment by mih** [comment]
Here my summary of the status quo of creating an setting a parameter input widget:

Command arguments pass to configure arrive here (this is the starting point):

https://github.com/datalad/datalad-gooey/blob/431abd2b3298f7ccfafc060753f9364b293646cc/datalad_gooey/param_form_utils.py#L40

In this function, parameter names and their default are determined

https://github.com/datalad/datalad-gooey/blob/431abd2b3298f7ccfafc060753f9364b293646cc/datalad_gooey/param_form_utils.py#L96

This get passed on to

https://github.com/datalad/datalad-gooey/blob/431abd2b3298f7ccfafc060753f9364b293646cc/datalad_gooey/param_form_utils.py#L167

which calls both

https://github.com/datalad/datalad-gooey/blob/431abd2b3298f7ccfafc060753f9364b293646cc/datalad_gooey/param_form_utils.py#L203

(which received the `default`, but does not use it (left-over from previous times), it should be removed as an argument)

and

https://github.com/datalad/datalad-gooey/blob/431abd2b3298f7ccfafc060753f9364b293646cc/datalad_gooey/param_widgets.py#L155

which passes the default on to a widget's `set_gooey_param_spec(name, default)`

After this (`_get_parameter_widget()`) is all done, a widget's `set_gooey_param_value(cmdkwargs[pname])` is called to set any given (non-default) parameter value

https://github.com/datalad/datalad-gooey/blob/431abd2b3298f7ccfafc060753f9364b293646cc/datalad_gooey/param_form_utils.py#L160

Within a widget, `set_gooey_param_spec(name, defaullt)` stores the `default` (in the mixin), and calls `set_gooey_param_default()` -- which by default does nothing, and could be implemented by particular widget to do something of unknown relevance.

On `get_gooey_param_spec()` (retrieval), `get_gooey_param_value()` is called. if that raises `ValueError`, a value of `_NoValue` is returned. This is described to be the case when

> when no value was gathered

This is also the case when the reported value is no different from the default stored within the mixin.

### Issues

With this setup, an input widget's state after complete initialization does not necessarily reflect a present default.

If this is desired, a number is things could be done differently...

### Possible changes

- The `default` could be set in any widget as the actual current state (unless replaced by an actual value)
- If that is done, there is now value in making the widget itself aware of a default vs any other value (unless one would want to provide a "reset" feature).
- Even with a reset feature, there is no need for a handling of a "default" anywhere outside the mixin, specifically not anywhere in an actual widget implementation. Resetting or setting a default, is merely setting a value matching a default.
- Therefore `set_gooey_param_default()` should be removed from the mixin API, only the private member setting inside `set_gooey_param_spec()` needs to stay. Consequently the call to `set_gooey_param_default()` in `set_gooey_param_spec()` needs to be removed too.
- Rather than setting the value of each widget to a default in each widget separately, and afterwards resetting the widget to a given value, as done now in

https://github.com/datalad/datalad-gooey/blob/431abd2b3298f7ccfafc060753f9364b293646cc/datalad_gooey/param_form_utils.py#L157-L159

defaults should be overwritten immediately in 

https://github.com/datalad/datalad-gooey/blob/431abd2b3298f7ccfafc060753f9364b293646cc/datalad_gooey/param_form_utils.py#L40

and only the effective value should be set once.

- Instead of calling
https://github.com/datalad/datalad-gooey/blob/431abd2b3298f7ccfafc060753f9364b293646cc/datalad_gooey/param_form_utils.py#L160

for this, all values for all parameters should be passed at once to a widgets

https://github.com/datalad/datalad-gooey/blob/431abd2b3298f7ccfafc060753f9364b293646cc/datalad_gooey/param_widgets.py#L131

(which should be renamed to ` init_gooey_from_params()`).

Providing all values for all parameters at once can help to avoid update cascades (e.g. when a `dataset` argument is already known at the start, and a parameter that needs it is updated before the `dataset` parameter widget is).

**Comment by mih** [comment]
I think it might additionally be good to implement a general parameter widget behavior:

- the mixin stores any set value, and thereby is also able to recognize the absence of a set value
- the value changed signal is triggered by comparison of an incoming value with the stored previous one
- any widget implementation needs to be wired up to report any user-set value to the mixin immediately, but calling `set_gooey_param_value()`

This way the implementation of a widget only needs to consider two aspects

- set a particular value in the widget programatically
- wire the widget up to report an interactively set value to `set_gooey_param_value()`

optionally a widget that needs it can implement some initialization (set choices, etc.) based on a trigger sent via `init_gooey_from_params()`

The rest is covered by the mixin.

**Comment by mih** [comment]
Most, if not all widgets will need to be able to handle `None`, even if their `Constraint` does not indicate it. `None` is a command default (frequently combined with stuff like `action=store_true`, or a `str` value (e.g. a message or None, rather than an empty message)

**Comment by mih** [comment]
Likely `MultiValue` also need to become aware of whether they are supposed to return unique value lists. This cannot be a general setting, but must come for a particular parameter context.
