### ISSUE TITLE
MVP operations checklist (collaborative edit!)

### ISSUE THREAD

**Issue by mih** [datalad/datalad-gooey#216]
Incomplete list of operations to test for the MVP (Simplified only!!) on all platforms. Please extend.

Checking a box means:

1. It has achieved the desired goal
2. The interface made sense, and it as clear an minimal as possible

If any of the two is not given, do not check the box but edit the item with a note (ideally a pointer to an issue).

- Create a dataset (outside any other) `Datasets -> Create`
  - [x] Linux
  - [x] Windows
  - [x] Mac

- Dataset -> Clone
  - `datalad clone https://github.com/psychoinformatics-de/studyforrest-data`
  - [x] Linux
  - [x] Windows
  - [x] Mac

- Right-click on dataset -> drop (entire dataset)
  - `Dataset().drop(what='all')`
  - [x] Linux
  - [x] Windows
  - [x] Mac

- Right-click on dataset -> drop recursively (entire dataset hierarchy)
  - `Dataset().drop(what='all', recursive=True)`
  - [x] Linux
  - [x] Windows
  - [x] Mac
 
- Right-click on local dataset -> drop (entire dataset w/o having pushed anywhere)
  - `Dataset().drop(what='datasets', reckless='kill')`
  - [x] Linux
  - [x] Windows
  - [x] Mac
  

- Create a sibling on GitHub without the correct token
  - [x] Linux
  - [x] Windows https://github.com/datalad/datalad-gooey/issues/125
  - [x] Mac

- Push changes to local sibling (while target is on another branch)
  - `Dataset().push(to='origin')`
  - [x] Linux
  - [x] Windows
  - [x] Mac

- Push changes to local sibling (while target is on same branch denying the update): Correct failure (minus issue #217)
  - `Dataset().push(to='origin')`
  - [x] Linux
  - [x] Windows
  - [x] Mac
 
- Update from a local sibling
  - `Dataset().get(sibling='clone')`
  - [x] Linux
  - [x] Windows
  - [x] Mac

- Right-click on dataset -> Get (entire dataset and subdatasets without data)
  - `Dataset().get(get_data=False, recursive=True)`
  - [x] Linux
  - [x] Windows
  - [x] Mac

**Comment by adswa** [comment]
everything is ticked

**Comment by mih** [comment]
Also tried `create` -> `save` -> `create-sibling-webdav` -> `push` -> `clone` and it worked on linux

**Comment by mih** [comment]
Done here.
