### ISSUE TITLE
Prevent double error reporting with `IncompleteResultsError`

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad-gooey#217]
Right click on annexed file and drop leads to double error reporting.

I get 
```
Running: Dataset('/tmp/NewDataset/subds').drop(path=[PosixPath('/tmp/NewDataset/subds/somefile')])

drop(error): somefile (file) [unsafe; Could only verify the existence of 0 out of 1 necessary copy; (Use --reckless availability to override this check, or adjust numcopies.)]

Running: Dataset('/tmp/NewDataset/subds').drop(path=[PosixPath('/tmp/NewDataset/subds/somefile')]) failed! (see error log for details)
```

in the `Command log` and the traceback of `IncompleteResultsError` in the `Error log` tab. That seems unnecessarily scary.

**Comment by mih** [comment]
That might be, but there is little that can be done about this. Unless there is an idea how to avoid it in general. I'd say this is "wont fix".

**Comment by bpoldrack** [comment]
Not yet sure. But I think it may be reasonable to treat `IncompleteResultsError` differently from an arbitrary exception. Didn't think that through entirely yet, though.

**Comment by mih** [comment]
Good point.
