### ISSUE TITLE
Must not give error dialog when `dataset` is not set

### ISSUE THREAD

**Issue by mih** [datalad/datalad-gooey#224]
`Dataset -> Push` gives immediate error, but a user never had the chance...

Maybe the `Dataset` menu should not list commands that require the context of a dataset to begin with?

**Comment by jsheunis** [comment]
Purely from the perspective of an uninformed user, I think this would make sense yes. Extra options that cannot be used without extra context/knowledge just lead to confusion.

**Comment by mih** [comment]
It will be difficult to remove commands from this menu. It is the only place to provide a full list. We might just call it `DataLad` instead of `Dataset`

**Comment by Manukapp** [comment]
I wonder whether `create` won't be as clear as `make into Datalad`, or `become Datalad`, `summon Datalad`, `transform into Datalad` (a bit long), `Dataladify` 

I was expecting that `create` would create a new folder.
