### ISSUE TITLE
Cloning into existing dir does not update annotation in tree view

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad-gooey#227]
Cloning and selecting a target path in the widget implies, that we `clone` to an existing directory (since the directory path selector does not allow to give a not yet existing path).
That does not trigger an annotation update in the tree widget. Since by default we have sorting by `Type` in the tree view, one would expect a new clone to show up at the top alongside other directories of type `dataset`. That does not happen.

**Comment by jsheunis** [comment]
Reproduced on a mac, for both `create` and `clone`.

**Comment by adswa** [comment]
Reproduced on Windows

**Comment by Manukapp** [comment]
Similarly, cloning does not work when designating the folder path, however no problem if path not specified. 

https://user-images.githubusercontent.com/86295664/192523365-948dba4e-1a14-48af-af46-ef0ba30dace4.mp4

**Comment by jsheunis** [comment]
After updating to datalad==0.17.6, the `create` operation works as expected here.
