### ISSUE TITLE
git-annex installation error (fluke) with installer

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-gooey#236]
The Windows installer on Windows 11 might stumble across an issue of the datalad installer when installing git-annex: https://github.com/datalad/datalad-installer/issues/92

![image](https://user-images.githubusercontent.com/29738718/192515709-3107b2e8-03ee-47cf-b392-a73430ecdaac.png)

The error is a fluke (as outlined in the issue in the installer, the installation actually succeeds), but annoying and confusing. cc @christian-monch

**Comment by mih** [comment]
Can we close this? I believe the gooey installer does not utilize the DataLad installer. Correct @christian-monch ?

**Comment by adswa** [comment]
No it seems its fetched from git-annex website directly (from https://github.com/datalad/datalad-gooey/blob/main/tools/installer_building/build_windows_installer.ps1):

> Fetch git annex for windows
Invoke-WebRequest -UseBasicParsing 'https://downloads.kitenet.net/git-annex/windows/current/git-annex-installer.exe' -OutFile ${sources_dir}\git-annex-64-bit.exe
