### ISSUE TITLE
Not Getting dataset (forrest) content

### ISSUE THREAD

**Issue by Manukapp** [datalad/datalad-gooey#244]
### Is it a new bug?

I did not find an existing issue about my problem

### What is the problem?

i cloned https://github.com/psychoinformatics-de/studyforrest-data, and then attempted to `datalad get` file contents from that repo, but `datalad get` displays that the selected folder is not an installed dataset. So I tried to `datalad create` this folder, but it failed again. See screen recording below.

May this be specific to this dataset?

### What steps will reproduce the problem?

1. Cloned github dataset
2. `datalad get` on a subfolder of the dataset
3. `datalad get` failed, saying not an installed dataset
4. `datalad create` to attempt to fix this, no success

[notgetting.webm](https://user-images.githubusercontent.com/86295664/192526874-f21ce633-6796-42af-acef-e2f2a3cbfcc2.webm)

### How did you install the App?

- [X] Using pip (``pip install datalad-gooey``)

### System information

Windows 10

**Comment by adswa** [comment]
ah yeah, this is #238. The issue is that you're attempting to get an uninstalled subdataset, and the get command automatically parametrizes the dataset path with this dataset. But to install the subdataset successfully, the dataset argument needs to be the superdataset 'studyforrest-data'
