### ISSUE TITLE
Come up with a facility to indicate "busy"

### ISSUE THREAD

**Issue by mih** [datalad/datalad-gooey#26]
Qt has many ways (status bar, cursor shape/type, ...), but we need to pick one, and wire things appropriately to have busy go on and off as needed.

Example use cases:

- FS browser items are still being annotated
- A command is running

**Comment by loj** [comment]
I vote for changing the cursor shape. I like [`WaitCursor`](https://doc.qt.io/qtforpython/PySide6/QtCore/Qt.html#PySide6.QtCore.PySide6.QtCore.Qt.CursorShape)

I didn't manage to figure out exactly how to do this yet, but I think we will want to use [setOverrideCursor](https://doc.qt.io/qtforpython/PySide6/QtGui/QGuiApplication.html#PySide6.QtGui.PySide6.QtGui.QGuiApplication.setOverrideCursor)
