### ISSUE TITLE
Dataset menu entries not sorted in any intelligible fashion

### ISSUE THREAD

**Issue by mih** [datalad/datalad-gooey#34]

**Comment by adswa** [comment]
I don't have a solution yet, I'm just posting my analysis for the reason of this issue.

The dataset method menu consist of a range of submenus corresponding to the command grouping defined in [datalad.interface.__init__.py](https://github.com/datalad/datalad/blob/master/datalad/interface/__init__.py). Unlike datalads ``--help`` command and other command overviews, the submenues are not sorted in their original order, which is based on specificness of commands (starting with essential commands and ending with misc commands).

![Screenshot from 2022-09-12 11-04-55](https://user-images.githubusercontent.com/29738718/189615189-299bee0b-de6d-48d0-8070-afcbea0bd3b6.png)

The reason for this is that the submenu generation in [`_generate_submenus`](https://github.com/datalad/datalad-gooey/blob/25780eb741b3728a31fdba0068ed0ea4afbb3dd3/datalad_gooey/dataset_actions.py#L79), which generates submenues in the right order, is detached from the assembly of available Dataset methods into the submenues in [`add_dataset_actions_to_menu`](https://github.com/datalad/datalad-gooey/blob/25780eb741b3728a31fdba0068ed0ea4afbb3dd3/datalad_gooey/dataset_actions.py#L12). The latter which loops through commands in alphabetical order, and inserts submenus corresponding to first command that's a part of it. If the first dataset method in alphabetical order isn't in the group of "essential commands", this will not be the first submenu entry. In the screenshot, the first method was `add_archive_content`, which happens to be a misc command, and thus this submenu is placed first.

Its not trivial to fix this. The loop through dataset methods is done to only list actually available methods, as the command sorting proided by datalad.interface does not necessarily define commands that are available in the specific dataset at hand.
