### ISSUE TITLE
Asking for a token splits important info into two different locations

### ISSUE THREAD

**Issue by mih** [datalad/datalad-gooey#340]
The input dialog just says "token", while in the command log it states "An access token is required for https://gin.g-node.org. Visit https://gin.g-node.org/user/settings/applications to create a token" -- which is much more useful, but in a different window in the background.

**Comment by bpoldrack** [comment]
Quick exploration suggests the issue is with `datalad-next` patching `create_sibling_gh`'s `_set_request_header`. In core this calls `ui.question` with that message as the title, but the patch seems to go via `CredentialManager.get`.

Looking further ...

**Comment by bpoldrack** [comment]
So, this is a two-part issue. Part one is, that `CredentialManager` splits those things - see https://github.com/datalad/datalad-next/pull/113

Part two is, that gooey's `ui.question` uses the `title` parameter as dialog title. This is intutive, but "wrong" as the `title` is meant for the prompting text. Addressing this next.
