### ISSUE TITLE
Use "file-open-dialog" for `path` command parameter configuration

### ISSUE THREAD

**Issue by mih** [datalad/datalad-gooey#35]
Right now this is still done with a line edit that cannot handle more than one path.

**Comment by loj** [comment]
Commands like `get` would greatly benefit from this. Typing in the `path` for a file that is deeply nested in a dataset is not so nice. Being able to select the file would be much more convenient. Perhaps with the `Q.FileDialog` widget (https://doc.qt.io/qtforpython/PySide6/QtWidgets/QFileDialog.html#qfiledialog)

**Comment by mih** [comment]
On it

**Comment by mih** [comment]
So this turns out to be complicated. Depending on the platform, selection dialogs can handle directories or files, but not both. In general, datalad does not tell us what type of paths (files, dirs, existing or possibly nonexisting) it expects for a given command.

There is a second issue: The number of paths. Many commands can handle more than one, so some kind of multi-select is needed to make the UI suitable for such commands. However, standard selection dialogs may support multiselect, but rarely across several directories.

So the required solution must provide means to select a path, and the ability to perform any number of such selections.

The need for multi-select is also present in other scenarios (think: `sections` in `wtf()`). Therefore it may be most appropriate to implement a generic widget that takes any other widget and is able to add/remove additional selections. For each individual selection it uses the provided widget type.

We could use this "multi-select" whenever a parameter has `action='append'` or `nargs="*"` or `nargs="+"` or any other indication of a multi-value parameter input.

**Comment by mih** [comment]
This is done now.
