### ISSUE TITLE
CredentialChoiceParameter/EnsureCredentialName does not allow to specify new credentials

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad-gooey#360]
Discovered in context of #341

credential parameter gives a line edit, but fails to pass on an entered value when it was not part of pre-existing choices. This makes it impossible to create new credentials in the process of a `create-sibling-*`.

**Comment by mih** [comment]
Seems worse than that: This is the terminal output

```
Traceback (most recent call last):
  File "/home/mih/hacking/datalad/gooey/datalad_gooey/param_widgets.py", line 370, in _handle_input
    self.set(None if not choice else choice, set_in_widget=False)
  File "/home/mih/hacking/datalad/gooey/datalad_gooey/param.py", line 163, in set
    val = self.get_constraint()(value) if value != _NoValue else value
  File "/home/mih/hacking/datalad/git/datalad/support/constraints.py", line 302, in __call__
    raise ValueError(f"value {value} is not one of {self._allowed}")
```

**Comment by adswa** [comment]
I also arrived at the conclusion that there is no gooey-internal support yet to set credentials interactively when they don't exist yet via Gooey. What bothers me, too, (though it is probably rather an issue for core) is that even if I leave the credential field blank, it will just pass the non-value as is, and then core decides to use a random token (it seems), without communication about this. In my case I don't understand how datalad determined that the specific eventual token would be useful, it took one I can't remember the origin story that doesn't have any realm and not even a secret set.

**Comment by mih** [comment]
Linking https://github.com/datalad/datalad-gooey/issues/341

This used to work....

**Comment by mih** [comment]
It looks like it

**Comment by bpoldrack** [comment]
> and then core decides to use a random token (it seems)

Actually, that's datalad-next. The patch for create-sibling-ghlike uses `netloc` to create a credential name in that case. It appears to then be used, although I can't get to see it existing with `datalad credentials`.
