### ISSUE TITLE
ssh console interaction not captured in GUI (at least in Windows)

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad-gooey#371]
The following was observed in Windows:

If ssh asks the user to accept a new host-key, the interaction is done in the controlling terminal. It does not become visible on the GUI. The GUI gives the impression that datalad_gooey is hanging, although it is just waiting at console input.

The best solution would be to let ssh prompt for user input in the GUI, but that might be difficult to achieve. Another solution might be to document it, or display a dialog that instructs the user to interact with the console

**Comment by mih** [comment]
Is this for an SSH connection that is opened by us specifically? Or indirectly via Git?

Maybe the setup to run things through `datalad sshrun` is missing and we could have a chance to handle this centrally.

**Comment by christian-monch** [comment]
The setup created by the new installer uses `datalad sshrun`(that was the fix for a part of issue #308). I will look whether I can get `sshrun.py ` to use `datalad-gooey-askpass` on windows.

**Comment by mih** [comment]
The app performs a basic setup aiming to prevent terminal interaction in its constructor. Maybe that is a starting point.

**Comment by christian-monch** [comment]
> The app performs a basic setup aiming to prevent terminal interaction in its constructor. Maybe that is a starting point.

Thx. Almost all is there, but windows also needs $DISPLAY (facepalm)
