### ISSUE TITLE
`datalad status` call is not restricted to directory

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-gooey#43]
With reference to [this code](https://github.com/datalad/datalad-gooey/blob/main/datalad_gooey/fsbrowser.py#L110-L114):

```python
# trigger datalad-status execution
# giving the target directory as a `path` argument should
# avoid undesired recursion into subDIRECTORIES
self._app.execute_dataladcmd.emit(
    'status', dict(dataset=dsroot, path=d))
```

This call does in fact recurse into a subdirectories. We could do the status call per child (that is not a directory) in the expanded directory. E.g.:

```python
# trigger datalad-status execution
# giving the target directory as a `path` argument should
# avoid undesired recursion into subDIRECTORIES
for dc in d.iterdir():
    if not dc.is_dir():
        self._app.execute_dataladcmd.emit(
            'status', dict(dataset=dsroot, path=dc, annex='basic'))
```

I've tested this locally and it works, but the annotations are then done one by one, which makes for a weird user experience. Also, with this approach we don't annotate any immediate subdirectories/subdatasets.

Any thoughts?

**Comment by mih** [comment]
There should be no neeed to make one-by-one call. We can simply take all non-dirs and pass them on at once (decision would need to be made re `dataset` types, but I think they too).

I am presently making changes that should make it unnecessary to use `d.iterdir()` and work directly with the model.
