### ISSUE TITLE
quit from drop-down menu

### ISSUE THREAD

**Issue by aqw** [datalad/datalad-gooey#52]
Currently I see no equivalent of File->Quit.

I assume that most people quit by hitting the "X" for the window (especially as keyboard interrupt doesn't yet work #38), I don't have such chrome when using my WM (sway), so I use keyboard shortcuts to close the application.

The number of people who will lack window chrome is vanishingly small. But, the File->Quit idiom is a common one. Given the target audience of the gooey-GUI, I think such a dialog would increase familiarity for a certain set of users.

**Comment by adswa** [comment]
@all-contributors please add @aqw for userTesting, ideas
