### ISSUE TITLE
File dialog only allows for the selection of file paths that are present

### ISSUE THREAD

**Issue by loj** [datalad/datalad-gooey#53]
For example, when using the `get` command to select a specific file path, files which are not present locally are not visible.

**Comment by mih** [comment]
This is bad. I did not find a way to show broken symlinks in any `QFileDialog` configuration. Not sure how to mitigate the situation.

Maybe implementing a dedicated proxy model would work https://doc.qt.io/qtforpython/PySide6/QtWidgets/QFileDialog.html#PySide6.QtWidgets.PySide6.QtWidgets.QFileDialog.setProxyModel

They mention this to be a way to "add drives". I take this as "adding stuff that would not normally be there".

**Comment by mih** [comment]
Solution identified by @aqw based on a hint by @bpoldrack 

`QFileDialog.setFilter()` can take any and all of https://doc.qt.io/qtforpython/PySide6/QtCore/QDir.html?highlight=filters#PySide6.QtCore.PySide6.QtCore.QDir.Filter
