### ISSUE TITLE
clone has issues

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad-gooey#84]
So, I tried to clone the openfmri dataset from `datasets.datalad.org`.

There's a bunch of observations. First things, first: Doesn't work:

- opened gooey on some regular directory and try to clone via main menu `Dataset`->`Essential commands`.
- give a destination path and url (`///openfmri` in my case) via  the command widget
- result: Nothing. No busy indication and nothing in the status bar and no cloning happening AFAICT.
- log: 
```
[snip the log from menu/widget creation]

{'path': '/tmp/somedir/opemfmri', 'source': '///openfmri'}
EXECINTHREAD clone {'source': '///openfmri', 'path': '/tmp/somedir/opemfmri'} None
```

Furthermore, trying this leads me to think it would be nice to have a context menu for directories as well (probably limited command set - `clone`, `create`) and have this directory be the CWD for the command call. This would allow to clone into a place selected by the tree view and have datalad derive the default target path within just like it works on command line. However, that's just convenience, obviously.

Edit: Note, that none of that changes if I do not use the `///` shortcut.

**Comment by jsheunis** [comment]
I can confirm this issue is happening for me as well. Both when cloning into a dataset, and when cloning into a parent directory of a path.

**Comment by bpoldrack** [comment]
FTR: Looks to me as if `_cmdexec_thread` is failing before the execution is even happening. That's because `exec_params` is `None` which should lead to `exec_params.get()` giving an `AttributeError`. That's the obvious part. What I don't know yet is whether it's okay for `exec_params` to be `None` in the first place.

**Comment by bpoldrack** [comment]
Ah, I think I found it:

`GooeyDataladCmdUI._retrieve_input` emits `configured_dataladcmd` and this one lacks the first argument.
