### ISSUE TITLE
UX: Initiating the dataset menu from a dataset is not always intuitive 

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-gooey#85]
An example of unintuitive behaviour: I would like to clone a dataset from a source URL into the current directory, but I cannot initiate the `clone` command from that directory item. I have to initiate it from a dataset and then have to specifically select the path using the widget, where the path might be some parent directory.

Ideally, a directory would also have a (limited) menu.

**Comment by mih** [comment]
Yes, this is the way. A dedicated context menu for any supported scenario:

- datasets (done)
- directories (this, immediately doable)
- annexd-files (waiting for https://github.com/datalad/datalad-gooey/issues/78)
- ...

**Comment by jsheunis** [comment]
I'll start working on this.

**Comment by adswa** [comment]
Partial 2c: In the context of #82 I am leaning towards having a flat list of applicable commands for directories.

**Comment by mih** [comment]
What would clicking on a directory do? For datasets, it parameterizes the command with a dataset argument.

For directories (and files), there could be any command in the menu that can take a `path` and the path of the item clicked on would set it.

Hand crafting a list will require constant maintenance, and will never cover datalad extensions that we have not seen yet.

It also makes sense to think about further annotation parameters in commands with these kinds of semantic info.

**Comment by jsheunis** [comment]
> What would clicking on a directory do? For datasets, it parameterizes the command with a dataset argument.

I was looking at it from the other viewpoint, e.g. I know I want to `create` or `clone` a dataset into a specific directory, so I expect to be able to have those options when I right-click on a directory. Re parameters, I've duplicated the basic `add_dataset_actions_to_menu` functionality for directories, and set the `dataset` argument to None. 

> For directories (and files), there could be any command in the menu that can take a path and the path of the item clicked on would set it.

Yes, the path could be set.

> Hand crafting a list will require constant maintenance, and will never cover datalad extensions that we have not seen yet.

Good point against handcrafting a list of commands.

> Partial 2c: In the context of https://github.com/datalad/datalad-gooey/issues/82 I am leaning towards having a flat list of applicable commands for directories.

I think I agree with this for the first functional version of the GUI. But in the long run I think it would need to be reworked to something more automatic. Perhaps an idea is to have the full list as for datasets, but exclude all commands that require a `dataset` argument?

**Comment by mih** [comment]
Alternatively, the path and the dataset argument could be set (i.e. save-in-datalad). It is cheap the figure it out.

**Comment by jsheunis** [comment]
Do you mean that the menu+submenu command options for a directory is set and presented in the same way as for a dataset, with the difference being that for a directory the `dataset` argument is set to `None` and the `path argument is set to the path of the directory?

**Comment by mih** [comment]
No, rather both are set. We no if a directory is in a dataset or not.

**Comment by jsheunis** [comment]
Ah ok, thanks for the clarification.

**Comment by jsheunis** [comment]
Ok, been looking for a way to see whether a directory is part of a datalad dataset or not, and nothing is obvious to me. Some ideas:
- Is there a way to do this easily with datalad for a given path?
- Should I recurse upwards through parents of parents of the applicable `FSBrowserItem` and check their `datalad_type` (or `data`) properties until I find a dataset (or not)?
- Should I do something with `Path.parents` and searching for `.datalad`?
- Or is this property already accounted for in the current code and I just didn't find it?

**Comment by mih** [comment]
Yes, there is. Grep for `get_dataset_root`. This makes the test directly on the FS. Searching through `item.parent()` is an alternative approach.

**Comment by mih** [comment]
Also note that we have now a `simplified` UI mode. For that one it makes sense to limit the choices to a few hand-picked operations, rather than including everything theoretically possible.

**Comment by mih** [comment]
I have implemented generic support for various types of context menus. Will push shortly.

**Comment by mih** [comment]
There are now dedicated context menus for `dataset`, `directory`, and `file` type items. The latter two have dedicated command sets for items within datasets too.
