### ISSUE TITLE
Prevent reloading SVG icons for every tree item

### ISSUE THREAD

**Issue by mih** [datalad/datalad-gooey#86]
Instead, have an icon provider that loads them as necessary, and hands out pointers if possible.

https://github.com/datalad/datalad-gooey/blob/662056036a349816547ba25fcfe57dca624e93d8/datalad_gooey/fsbrowser_item.py#L163

**Comment by jsheunis** [comment]
would it make sense to just load all possible QIcon objects up front (there are about 12) and then just use those pointers in the `_getIcon` selector?

**Comment by mih** [comment]
I went for lazy loading, but otherwise yes, that.
