### ISSUE TITLE
Windows: datalad-gooey entrypoint seemingly effectless

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-gooey#96]
Might only be an FYI, not a bug: Running ``datalad-gooey`` in a terminal does not open up the GUI.
``datalad gooey`` works fine; i.e., open the GUI in a Window.

**Comment by Manukapp** [comment]
**On a Windows' command prompt** 
`datalad gooey` prompts a folder search if no path is given. It does not open GUI of current directory.
`datalad-gooey` does not work in unix termnal. On window's cmd prompt, a series of flashing command prompts appear and then disappear.

**Comment by mih** [comment]
Is this still the case?

**Comment by mih** [comment]
Yes, still the case, Michael!

It is also hard to debug for a windows noob like me. The entrypoint "script" is a `.exe`, hard to tell what it is trying.
