### ISSUE TITLE
Get an 'initial directory'-choosing dialoque

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-gooey#97]
starting datalad gooey from the explorer in Windows opens System32, with no means to navigate out of it (only further down). I doubt that windows users will navigate into a directory in a terminal to start it. Alternatively, we could maybe try to add a "open datalad gooey here" option in the right-click menu in the explorer, like Git for Windows does.

**Comment by mih** [comment]
Yes, a dialog makes sense. Also choosen HOME on windows, rather than PWD is a sensible thing too.

Maybe that would even make sense in general. We should add a desktop file and see how menu integration works on linux too.

**Comment by mih** [comment]
Done via #102
